import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  Box,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarClock,
  CheckCheck,
  Circle,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  FileCheck,
  FileClock,
  FileText,
  Fingerprint,
  Folder,
  GitFork,
  HandCoins,
  History,
  Home,
  Inbox,
  Landmark,
  Layers,
  LayoutGrid,
  List,
  LogIn,
  MailPlus,
  Megaphone,
  MessageSquareWarning,
  Network,
  PhoneCall,
  Receipt,
  RefreshCw,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Split,
  SquareKanban,
  Sun,
  Table,
  Target,
  Timer,
  Truck,
  User,
  UserCheck,
  UserPlus,
  UserSearch,
  UserX,
  Users,
  Wallet,
  WalletCards,
  type LucideIcon,
} from 'lucide-react';

/**
 * Peta nama ikon (gaya kebab Lucide, sama seperti prototype `js/shell.js`)
 * ke komponen `lucide-react`. Ditulis eksplisit — bukan lookup dinamis —
 * supaya bundle tetap ter-tree-shake.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'badge-check': BadgeCheck,
  banknote: Banknote,
  'bar-chart-3': BarChart3,
  bell: Bell,
  box: Box,
  briefcase: Briefcase,
  'building-2': Building2,
  calculator: Calculator,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'check-check': CheckCheck,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  coins: Coins,
  contact: Contact,
  'file-check': FileCheck,
  'file-clock': FileClock,
  'file-text': FileText,
  fingerprint: Fingerprint,
  folder: Folder,
  'git-fork': GitFork,
  'hand-coins': HandCoins,
  history: History,
  home: Home,
  inbox: Inbox,
  landmark: Landmark,
  layers: Layers,
  'layout-grid': LayoutGrid,
  list: List,
  'log-in': LogIn,
  'mail-plus': MailPlus,
  megaphone: Megaphone,
  'message-square-warning': MessageSquareWarning,
  network: Network,
  palmtree: Sun,
  'phone-call': PhoneCall,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  'scroll-text': ScrollText,
  settings: Settings,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  split: Split,
  'square-kanban': SquareKanban,
  table: Table,
  target: Target,
  timer: Timer,
  truck: Truck,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-search': UserSearch,
  'user-x': UserX,
  users: Users,
  wallet: Wallet,
  'wallet-cards': WalletCards,
};

export function NavIcon({ name, className }: { name?: string; className?: string }) {
  if (!name) return null;
  const Icon = ICONS[name] ?? Circle;
  return <Icon className={className} />;
}

